### ISSUE TITLE
Dependence on shamsi_date library

### ISSUE THREAD

**Issue by FatulM** [PersianFlutter/persian-datetime-picker#27]
Please depend on shamsi_date library instead of copying it's code.
Since there are people who make issues on `shamsi_date` and I think their problem is about usage of outdated `shamsi_date` version. Depending on library has this advantage that when I fix some issue or add some new feature you will automatically get it. 😄 😅
If you have problems with depending on library please inform me.
Thanks.

**Comment by M-amir-M** [comment]
Ok,I had many problems with shamsi_date package and I tried to contact with you but I was not successful.
And I had to copy the code and do some change.

**Comment by FatulM** [comment]
How did you try to contact ? 😅
We are connected with each other at LinkedIn ! 😁
Ok, thanks ...

**Comment by FatulM** [comment]
And also one problem I once found on this repository was that:

For example you were using
`int.parse(date.formatter.y)`
Which should be replaced with
`date.year`

I didn't check if it is fixed by now ...

**Comment by FatulM** [comment]
Hi,
Please check out my pull request (#85).
