### ISSUE TITLE
Year and Month picker in DatePicker

### ISSUE THREAD

**Issue by payam-zahedi** [PersianFlutter/persian-datetime-picker#3]
I just wanted to use this library to get birth dates. but after using it I understood that I can't use a year or month picker inside the date picker. Imagine that the user wants to enter it's birthdates to the app, the problem is he/she should use arrow buttons for changing month so many times. It would be awesome if when I click on year text, the year modal appears and after changing year, I can enter my birthday in.

I suggest to check out Native date picker dialog.

**Comment by M-amir-M** [comment]
Fixed this issue, if there is a problem please note that.
