### ISSUE TITLE
مشکل پس از بروز رسانی نسخه ی فلاتر به 2.8

### ISSUE THREAD

**Issue by erfanh3h** [PersianFlutter/persian-datetime-picker#33]
سلام وقت بخیر
پس از بروزرسانی فلاتر به جدیدترین نسخه پکیج با مشکل زیر روبرو شده است :

![Screenshot 2021-12-09 144739](https://user-images.githubusercontent.com/30592506/145387161-4c52ff3e-a0a4-4b02-9af8-7cd6c88b3388.png)

ممنون میشم نسخه ی جدید رو ارائه بفرمایید

**Comment by prooshani** [comment]
https://github.com/PersianFlutter/persian-datetime-picker/issues/34#issuecomment-990360861

**Comment by M-amir-M** [comment]
Fixed.
Update to 2.4.0
