### ISSUE TITLE
update to flutter 2.8

### ISSUE THREAD

**Issue by PouryaNoufallah96** [PersianFlutter/persian-datetime-picker#34]
سلام خوبید ؟ ببخشید مزاحم شدم . در رابطه با فلاتر خواستم بگم به ورزن ۲.۸ که آپدیت کردم دیگه برنامه هایی که persian dare picker 2.3.0 استفاده کردم ارور میده 
خواستم ببینم میتونید یه راهنمایی کنید ؟ یا اینکه باید آپدیت بدید؟

**Comment by prooshani** [comment]
میتونید از این نسخه استفاده کنید موقتا تا مالک پکیج آپدیت رسمی خودش رو ارائه بده.
```
persian_datetime_picker:
    git:
      url: https://github.com/prooshani/persian-datetime-picker.git
```

**Comment by M-amir-M** [comment]
fixed 
update to 2.4.0
