### ISSUE TITLE
issue for flutter 2.8

### ISSUE THREAD

**Issue by alikhajavi74** [PersianFlutter/persian-datetime-picker#35]
plz upgrade your package for compatibility with flutter 2.8

i receive this error:
Error: Type 'WhitelistingTextInputFormatter' not found  ...

**Comment by prooshani** [comment]
You can use this fork for now to solve the problem and wait for the author to update the package.

```
persian_datetime_picker:
    git:
      url: https://github.com/prooshani/persian-datetime-picker.git
```

**Comment by M-amir-M** [comment]
Fixed.
Update to 2.4.0
