### ISSUE TITLE
help Text isn't responsive

### ISSUE THREAD

**Issue by Alitaheri1374** [PersianFlutter/persian-datetime-picker#37]
لطفا اگه امکانش هست ویجت
 help Text
  که در بالا نمایش داده میشه رو ریسپانسیو کنید  

![pic](https://user-images.githubusercontent.com/95956422/145668349-e0186427-1628-447a-9eff-063cd7e1b6f0.jpg)

**Comment by M-amir-M** [comment]
@Alitaheri1374  fixed on 2.5.0
