### ISSUE TITLE
A RenderFlex overflowed by 2.0 pixels on the bottom.

### ISSUE THREAD

**Issue by androidwoman** [PersianFlutter/persian-datetime-picker#43]
![71d6947c-4037-47b6-bbca-3b8d0c0275e1](https://user-images.githubusercontent.com/76970164/158050009-c789fcc0-8277-408a-a457-ec8130e499d4.jpg)

**Comment by M-amir-M** [comment]
@androidwoman  fixed on 2.5.0, check it out :)
