### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by hamidjalili59** [PersianFlutter/persian-datetime-picker#45]
hi bro 😉
we have a serious problem in the new flutter version
![image](https://user-images.githubusercontent.com/42936283/169508278-240362f2-d96a-4b18-9a79-cf27b4d2f0cd.png)
please check it ty 🤗
thanks for great package

**Comment by P-B1101** [comment]
I create a #44 PR. just need to be merged.

**Comment by M-amir-M** [comment]
@hamidjalili59  fixed on 2.5.0, check it out :)
